/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package integrador.Interfaz;

import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Administrador
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public void setBtnExit(JButton btnExit) {
        this.btnExit = btnExit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuCompras = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenu();
        menuConvenios = new javax.swing.JMenu();
        menuEstaciones = new javax.swing.JMenu();
        menuLineas = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(575, 460));
        setMinimumSize(new java.awt.Dimension(574, 459));
        setPreferredSize(new java.awt.Dimension(574, 459));

        btnExit.setText("Salir");
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        menuInicio.setText("Inicio");
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInicio);

        menuCompras.setText("Compras");
        jMenuBar1.add(menuCompras);

        menuUsuarios.setText("Usuarios");
        jMenuBar1.add(menuUsuarios);

        menuConvenios.setText("Convenios");
        jMenuBar1.add(menuConvenios);

        menuEstaciones.setText("Estaciones");
        menuEstaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEstacionesMouseClicked(evt);
            }
        });
        menuEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstacionesActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuEstaciones);

        menuLineas.setText("Lineas");
        menuLineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLineasMouseClicked(evt);
            }
        });
        menuLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLineasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuLineas);

        menuReportes.setText("Reportes");
        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(484, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void menuLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLineasActionPerformed
    }//GEN-LAST:event_menuLineasActionPerformed

    private void menuEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstacionesActionPerformed
    }//GEN-LAST:event_menuEstacionesActionPerformed

    private void menuEstacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEstacionesMouseClicked
                Point p = this.getLocation(); 
        MantenimientoEstacion frmManEstacion = new MantenimientoEstacion();
        this.setVisible(false);
                        frmManEstacion.setLocation(p);
        frmManEstacion.setVisible(true);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_menuEstacionesMouseClicked

    private void menuLineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLineasMouseClicked
        
        Point p = this.getLocation();
        MantenimientoLinea frmManLinea = new MantenimientoLinea();
        this.setVisible(false);
        frmManLinea.setLocation(p);
        frmManLinea.setVisible(true);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuLineasMouseClicked

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        Point p = this.getLocation();
        Main frmMain = new Main();
        this.setVisible(false);
        frmMain.setLocation(p);
        frmMain.setVisible(true);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuInicioMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuConvenios;
    private javax.swing.JMenu menuEstaciones;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuLineas;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
