/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package integrador.Interfaz;

import java.awt.Point;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Administrador
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setUIDesign();
    }

    private void setUIDesign() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public void setBtnExit(JButton btnExit) {
        this.btnExit = btnExit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuCompras = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenu();
        menuConvenios = new javax.swing.JMenu();
        menuEstaciones = new javax.swing.JMenu();
        menuLineas = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(10, 10, 800, 600));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(574, 459));

        btnExit.setText("Salir");
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        menuInicio.setText("Inicio");
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInicio);

        menuCompras.setText("Compras");
        menuCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuComprasMouseClicked(evt);
            }
        });
        menuCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComprasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuCompras);

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuariosMouseClicked(evt);
            }
        });
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuUsuarios);

        menuConvenios.setText("Convenios");
        menuConvenios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuConveniosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuConvenios);

        menuEstaciones.setText("Estaciones");
        menuEstaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEstacionesMouseClicked(evt);
            }
        });
        menuEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEstacionesActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuEstaciones);

        menuLineas.setText("Lineas");
        menuLineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLineasMouseClicked(evt);
            }
        });
        menuLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLineasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuLineas);

        menuReportes.setText("Reportes");
        menuReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReportesMouseClicked(evt);
            }
        });
        menuReportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuReportesMouseDragged(evt);
            }
        });
        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {
            dispose();
            finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void menuLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLineasActionPerformed
    }//GEN-LAST:event_menuLineasActionPerformed

    private void menuEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEstacionesActionPerformed
    }//GEN-LAST:event_menuEstacionesActionPerformed

    private void menuEstacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEstacionesMouseClicked

        try {
            Point p = this.getLocation();
            MantenimientoEstacion frmManEstacion = new MantenimientoEstacion();
            frmManEstacion.setLocation(p);
            frmManEstacion.setVisible(true);
            this.setVisible(false);
            try {
                this.finalize();
            } catch (Throwable ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }     // TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_menuEstacionesMouseClicked

    private void menuLineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLineasMouseClicked

        Point p = this.getLocation();
        MantenimientoLinea frmManLinea = new MantenimientoLinea();
        frmManLinea.setLocation(p);
        frmManLinea.setVisible(true);
        this.setVisible(false);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuLineasMouseClicked

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        Point p = this.getLocation();
        Main frmMain = new Main();
        frmMain.setLocation(p);
        frmMain.setVisible(true);
        this.setVisible(false);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuInicioMouseClicked

    private void menuReportesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportesMouseDragged
    }//GEN-LAST:event_menuReportesMouseDragged

    private void menuReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReportesMouseClicked
        Point p = this.getLocation();
        Reporte frmReporte = new Reporte();
        frmReporte.setLocation(p);
        frmReporte.setVisible(true);
        this.setVisible(false);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuReportesMouseClicked

    private void menuConveniosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuConveniosMouseClicked

        try {
            Point p = this.getLocation();
            MantenimientoConvenio frmConvenio = new MantenimientoConvenio();
            frmConvenio.setLocation(p);
            frmConvenio.setVisible(true);
            this.setVisible(false);

            try {
                this.finalize();
            } catch (Throwable ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }        // TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_menuConveniosMouseClicked

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseClicked

        Point p = this.getLocation();
        MantenimientoUsuario frmConvenio = new MantenimientoUsuario();
        frmConvenio.setLocation(p);
        frmConvenio.setVisible(true);
        this.setVisible(false);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_menuUsuariosMouseClicked

    private void menuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComprasActionPerformed
    }//GEN-LAST:event_menuComprasActionPerformed

    private void menuComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuComprasMouseClicked
        Point p = this.getLocation();
        MantenimientoCompra frmCompra = new MantenimientoCompra();
        frmCompra.setLocation(p);
        frmCompra.setVisible(true);
        this.setVisible(false);

        try {
            this.finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_menuComprasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuConvenios;
    private javax.swing.JMenu menuEstaciones;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuLineas;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
