/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package integrador.Interfaz;

import integrador.dominio.FachadaInterfaz;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Administrador
 */
public class Mantenimiento extends Main  implements Observer {

    public FachadaInterfaz objFI;
    /**
     * Creates new form Mantenimiento
     */
    public Mantenimiento() {
        initComponents();
        this.objFI = new FachadaInterfaz();
        this.setMaximumSize(this.getPreferredSize());
        objFI.addObserver(this);
    }

    public JScrollPane getScrollPanelTable() {
        return scrollPanelTable;
    }

    public void setScrollPanelTable(JScrollPane scrollPanelTable) {
        this.scrollPanelTable = scrollPanelTable;
    }

   public JButton getBtnAlta() {
        return btnAlta;
    }

    public void setBtnAlta(JButton btnAlta) {
        this.btnAlta = btnAlta;
    }

    public JButton getBtnBaja() {
        return btnBaja;
    }

    public void setBtnBaja(JButton btnBaja) {
        this.btnBaja = btnBaja;
    }

    public JButton getBtnMod() {
        return btnMod;
    }

    public void setBtnMod(JButton btnMod) {
        this.btnMod = btnMod;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JTable getTableItems() {
        return tableItems;
    }

    
    public   void setTableItems(JTable tableItems) {
        this.tableItems = tableItems;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        scrollPanelTable = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableItems.setMaximumSize(new java.awt.Dimension(300, 64));
        tableItems.setMinimumSize(new java.awt.Dimension(300, 64));
        scrollPanelTable.setViewportView(tableItems);

        btnAlta.setText("Alta");

        btnMod.setText("Modificar");

        btnBaja.setText("Eliminar");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(btnBaja)
                        .addGap(18, 18, 18)
                        .addComponent(btnMod)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja)
                    .addComponent(btnMod))
                .addGap(18, 18, 18)
                .addComponent(scrollPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
    }//GEN-LAST:event_btnBajaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane scrollPanelTable;
    private javax.swing.JTable tableItems;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
    }
}
